version: '3'
services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data/redis:/data
    restart: always

  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'pgpass'
      POSTGRES_DB: 'test'
    volumes:
     - ./postgres/data/postgres:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'qa_pass'
      MYSQL_USER: 'qa_user'
      MYSQL_PASSWORD: 'qa_pass'
      MYSQL_DATABASE: 'qa'
    volumes:
      - ./mysql/data:/var/lib/mysql
  
  db-adminer:
    image: adminer
    restart: always
    ports:
      - 9005:8080

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/html:/var/www/html

  php:
    build: ./php
    ports:
        - "9000:9000"
    volumes:
        - "./php/html:/var/www/html"

  sbt:
    image: warriortrading/mvn_jdk11_compiler:DEV-9

  

